### ISSUE TITLE
Write poll scrapper

### ISSUE THREAD

**Issue by AlexAndorra** [pollsposition/models#7]
Write python program to automatically scrap polls for presidential elections 2022 from [this page](https://fr.wikipedia.org/wiki/Liste_de_sondages_sur_la_prochaine_%C3%A9lection_pr%C3%A9sidentielle_fran%C3%A7aise), used afterwards by the models.
**Issue up for grabs!**

**Comment by AlexAndorra** [comment]
Where are we on this @rlouf ? Do we already have a robust, automated way of getting the 2022 polls? Then I can run the model on those 🤩

**Comment by rlouf** [comment]
Well I'm not very automated but very robust for sure.

**Comment by AlexAndorra** [comment]
Just wanted to check 😜 Joking aside, it's probably a good idea to do a call with you showing me the process, so that we both can run the whole pipeline (including the model)

**Comment by AlexAndorra** [comment]
@rlouf brilliantly took care of this
